### ISSUE TITLE
Feedback for “Microsoft Flight Simulator 2020”

### ISSUE THREAD

**Issue by mb-simulations** [smyalygames/flightsim-on-linux#3]
Thank you for this project. It helped me get started with installing addons for MSFS on Linux.

One thing I am struggling with is Simconnect. I was not able to connect Navigraph Simlink and Simtoolkit Pro to the simulator. Also I was able to setup and install Swift for Vatsim, it recognized the installation of my sim and the ai models but it also does not connect to the simulator.

I am suspecting an issue with DotNET to be the reason for the problem but no matter what I cannot get SimConnect to run.

Do you have any hints for me on this problem?

**Comment by smyalygames** [comment]
Hiya, I'm glad you're using my little project :D

I'm also happy to help you out :)

Anyways, for the SimToolkitPro, I realised I completely forgot to mention that Simconnect has to be installed, it should be provided in the zip for downloaded for the STKP Simconnect Server as `SimConnect.msi`. I have forgotten to install that myself sometimes...

But in regards to Simlink, I am not entirely sure if it uses Simconnect or something else. Just to double check as you haven't been able to connect to the simulator on those 3 programs, have you installed them with Protontricks in the MSFS profile and also not using Wine? Because I have tried using the Fenix on a separate profile with DotNET which it would not manage to detect MSFS. 

In regards to Swift, I have written a guide but haven't gotten around to finishing it up and publishing it, but you can try the guide for Swift here: https://6906c99f.flightsim-on-linux.pages.dev/msfs/utils/vatsim. I think I gave up on step 4 as I didn't know if it would have been useful or if I was overcomplicating it.

But in regards to DotNET, you are using Mono right? Because I haven't gotten problems with Simconnect on Mono

**Comment by smyalygames** [comment]
Wait, I am so silly, I assume you've already installed Simlink on your MSFS Protontricks profile as the guide provides you the only way of logging in haha

But you may wanna check the logs for hints or you could send it here for Simlink, it's located in `PATH-TO-COMPDATA/1250410/pfx/drive_c/users/steamuser/Application Data/navigraph-hub/logs/`

Also another tip for debugging is running Protontricks through the terminal with `protontricks 1250410 --gui` as you get logs from applications that you opened this way

**Comment by mb-simulations** [comment]
Thank you for the quick answer. I did not realize you have a guide for Swift but it's basically what I did too :)

I have not experimented that much with wine until now. I only have some basic experience with steam proton games but all of them usually worked without much tinkering.

I did install Swift via Protontricks into the MSFS prefix. It also seems to recognize the sim it found the installation folders and was able to load the installed models. Just the connection to the sim does not seem to run. First I tried to install vPilot since it's what I'm used to but I gave up after 3 days of troubleshooting :D I installed and uninstalled .NET in different ways via protontricks and winetricks since I figured it's probably needed.

I am not sure about mono, I don't really know anything about it or how to set it up. Is it installed by default? Maybe I screwed it up by installing .NET because vPilot did not work... I might try later to setup a new prefix and install swift into that.

**Comment by smyalygames** [comment]
No worries at all :)

That's alright, I learnt about wine through days of experimenting, because there's like literally nothing available, and it has resulted in me reinstalling MSFS multiple times haha.

And I see that you have done the same thing as me before with installing .NET multiple times in hopes of getting an addon working (it has only caused more problems each time for me).

But I *think* Mono usually is installed by default in Proton. However if you're not sure, you could download and install it directly from here: https://wiki.winehq.org/Mono#Prefix_Local_Install, just check the Wine version you are running with the Mono version you're downloading.

At this stage, I would recommend you to reinstall MSFS as it would save the most amount of headaches. Usually the way I do it is just moving the `Microsoft Flight Simulator` folder in `%appdata%`, outside of your MSFS compdata folder, then uninstall, and install it again through Steam, run it, and once it asks you for the 160gb update, just close it and replace `Microsoft Flight Simulator` folder in your new compdata, and it should save you hours of downloading it again.

I have updated the STPK guide just now and I will published the VATSIM guide for, and apologies for not publishing it earlier and making you waste 3 days :(

But if you have any other questions, feel free to let me know :))

**Comment by mb-simulations** [comment]
I'll try that thanks! I'll let you know if it worked.

No worries, would've wasted alot more time probably if I didn't stumble over your guides.

Just curious, which Proton version do you use currently for MSFS? I just got the newest GE 9-7 when I set it up. Maybe I need an older version.

**Comment by smyalygames** [comment]
Awesome, I'd love to hear when you've managed to get it working :)

But I usually just use the latest GE, the I think the last one I tested was 9-5, but I think 9-7 should be fine from the changelog, I just haven't been played MSFS for the past few weeks. And also I've found GE to work better than normal Proton most of the time

**Comment by mb-simulations** [comment]
Did a reinstall exactly as you said. But still no connection with the sim itself...

![Screenshot from 2024-06-12 14-01-21](https://github.com/smyalygames/flightsim-on-linux/assets/93071864/f2dd2505-43c8-4ca2-9fc2-abe43bd86016)

![Screenshot from 2024-06-12 14-02-11](https://github.com/smyalygames/flightsim-on-linux/assets/93071864/ca11ebbc-ecc9-4faf-9ac7-2d1b4d765924)

**Comment by smyalygames** [comment]
In swift launcher, are you using standalone or GUI and core? Because it may be best to test it with standalone only first if you are running two instances of swift on Windows and Linux.

In standalone, open the GUI, then go into settings and make sure FS2020 is the only one enabled for now, and then next to the "No plugin loaded", you can click check again to see if it will find FS2020. Hopefully that should resolve the problem

**Comment by mb-simulations** [comment]
Just to make sure we are talking about the same :)

I have installed Swift directly into the proton prefix. I am not using it natively on linux. I have never used swift before.
I tried the standalone and also the core because I wasn't sure about the difference.

I tried to select only MSFS2020 and check again but it did not connect to the sim. On the network page it says "No simulator" I still have a feeling that something might be wrong with simconnect.

There are a few warnings in the log but not sure if they are relevant to the issue.

![Screenshot from 2024-06-12 14-57-52](https://github.com/smyalygames/flightsim-on-linux/assets/93071864/5b8a98ed-49da-4736-bd6d-b57d853e2ad6)

![Screenshot from 2024-06-12 14-58-47](https://github.com/smyalygames/flightsim-on-linux/assets/93071864/847708cb-6f0e-4a48-b1f9-8b07bac1cfac)

**Comment by smyalygames** [comment]
Thank you for explaining it, and yes, Swift is quite a steep learning curve compared to vPilot annoyingly.

I think the confusion stemmed as at first you selected this mode where my cursor is, which enables Swift Core (this acts like a server to communicate to a client, Swift GUI, usually on a different computer or could be another client on native Linux in this case), but the standalone version is the one that should be selected:
![image](https://github.com/smyalygames/flightsim-on-linux/assets/7905095/2519e95b-d883-4677-9a85-3362b17a4050)

But could you load in to an airport, and check that FS2020 is the only one selected on the screenshot below, and then click "check again"?

![image](https://github.com/smyalygames/flightsim-on-linux/assets/7905095/67d942d6-0ef6-432b-862b-df6bb670687a)

The warnings do not seem to be a problem as the OpenType ones are related to fonts and the URL one is related to Swift DB which shouldn't affect the connection to MSFS

I can't connect to my own simulator right now as I am forced to download SU15

**Comment by mb-simulations** [comment]
Thanks for the explanation and sorry for annoying you with my issues but it's really hard to even find someone who installs MSFS on linux haha 

_But could you load in to an airport, and check that FS2020 is the only one selected on the screenshot below, and then click "check again"?_

That's exactly what I did before and it did not work. I think somehow simconnect is not running or starting correctly but not sure how I could debug this or even find logs from it... Maybe some DLL that's not being loaded or something like that. I tried Proton GE 9-5 now too but did not do any difference. Also 64 and 32 Bit of Swift did not change anything.

Really weird... Not being able to fly on Vatsim since I have around 3000h on it and only fly on Vatsim is really the only thing holding me back from making the switch to linux for sure. I am already using linux for other games and on my laptop for a long time but just can't figure this out.

**Comment by mb-simulations** [comment]
[swiftguistd_240612131912_32.log](https://github.com/user-attachments/files/15806133/swiftguistd_240612131912_32.log)

Not sure if the swift log is of any help.

**Comment by smyalygames** [comment]
It's all fine, don't worry about it, you're not annoying me at all.

Thank you for the logs by the way. It is a really interesting problem considering I get this in my logs even before the simulator was fully running and I can't find it in your logs. And my swift did manage to connect to it.
```
[swift.driver]
15:15:54 info: Loaded and resolved MSFS symbols from SimConnect.dll: 'SimConnect.MSFS'
```

Maybe the problem may be that MS C++ dependencies are not installed? Because I am currently on my laptop instead of my PC with not much configuration to MSFS (other than ORBX scenery and the PMDG 737) and I found C++ deps installed. You could try installing them through Protontricks:

![image](https://github.com/smyalygames/flightsim-on-linux/assets/7905095/0405171e-bd55-4d90-acaf-d549e3bcf2cc)

**Comment by smyalygames** [comment]
I took a bit more of a look, it might be worth checking that you have `SimConnect.dll` in Steam install for MSFS. You can check by going onto Steam, right click MSFS -> Manage -> Browse local files, and you should see `SimConnect.dll` there.

**Comment by mb-simulations** [comment]
Thank you very much for your help!

The SimConnect DLL was already there but unfortunately also the vcrun2022 did not help.
I noticed you're on the beta of swift according to the screenshot, I was on the alpha and tried the beta but also did not work.

Really out of ideas here :(

**Comment by smyalygames** [comment]
Hmmm I did take a look through the new logs, they look quite similar to mine, other than I found that when the connection occurs, this should show up
```
15:53:17 info: Connect to org.swift-project.plugins.simulator.msfs: 'Name: 'KittyHawk' Version: 11.0.282174.999 SimConnect: 11.0.62651.3'
```

I think best step to take now is to try installing Navigraph Simlink, and just testing if it will connect to MSFS. Because it should require no tinkering other than to configure logging in to Simlink.

It may also help solve the problem as I think it installs some other libraries.

If not, could you also send a screenshot of the uninstaller of everything installed? You can find it here on Protontricks:

![image](https://github.com/smyalygames/flightsim-on-linux/assets/7905095/d9f2982e-00ee-48e8-9541-8da871d0dc59)

And I'm sorry that this is taking so long to figure out :(

**Comment by smyalygames** [comment]
Ayooo I'm glad you finally got it working :D

I am kind of surprised that flatpak was an issue, I wouldn't have thought so. But I've never used flatpaks, so I am not entirely sure how they work. My assumption is that it's some problem with sandboxing, and that you'd need to create an alias for protontricks to run a flatpak version of protontricks.

It's strange that fsync is not automatically enabled on protontricks, as it seems to run for me as I get this in my logs: `fsync: up and running.`

Anyways, if you want a fix for this, you can edit the desktop entries you've created by adding that environment variable yourself in `Exec=`, for example for Swift:
```
[Desktop Entry]
Name=Swift Launcher (Proton)
Exec=WINEFSYNC=1 protontricks -c "wine C:/Program\\ Files/swift-0.12-64bit/bin/swiftlauncher.exe" 1250410
Type=Application
StartupNotify=true
Categories=Game;Simulation;
```

I'm really glad you're happy now :) If you'd want, you can add me on Discord, my username is the same username as on github
